// <auto-generated />
using System;
using Hotelio.BookingService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotelio.BookingHistoryService.Migrations
{
    [DbContext(typeof(HistoryDbContext))]
    [Migration("20260110152626_LowerCaseTableNames")]
    partial class LowerCaseTableNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotelio.BookingService.DailyStatistic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("AverageBookingValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("BookingCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("TotalRevenue")
                        .HasPrecision(15, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("dailystatistics", (string)null);
                });

            modelBuilder.Entity("Hotelio.BookingService.HotelStatistic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("AverageBookingValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("BookingCount")
                        .HasColumnType("integer");

                    b.Property<string>("HotelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalRevenue")
                        .HasPrecision(15, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique();

                    b.ToTable("hotelstatistics", (string)null);
                });

            modelBuilder.Entity("Hotelio.BookingService.UserStatistic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BookingCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastBookingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("TotalSpent")
                        .HasPrecision(15, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("userstatistics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
