server:
  port: 8082

spring:
  application:
    name: booking-history-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: booking-history-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true

logging:
  level:
    com.hotelio: INFO
    org.springframework.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"