server:
  port: 8081

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://booking-db:5432/booking
    username: booking
    password: booking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3

grpc:
  server:
    port: 9090
    address: 0.0.0.0

logging:
  level:
    com.hotelio: DEBUG