version: v1
replicaCount: 2

image:
  name: booking-service
  tag: v1
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: ENABLE_FEATURE_X
    value: "false"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

labels:
  version: v1