grpc:
  server:
    port: 9090

spring:
  application:
    name: booking-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/booking}
    username: ${SPRING_DATASOURCE_USERNAME:booking}
    password: ${SPRING_DATASOURCE_PASSWORD:booking}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

monolith:
  url: ${MONOLITH_URL:http://hotelio-monolith:8080}
