replicaCount: 3

image:
  name: booking-service
  tag: prod
  pullPolicy: Never

env:
  - name: ENABLE_FEATURE_X
    value: "true"

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"