replicaCount: 1

image:
  name: booking-service
  tag: v0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  # Требуется задать requests и limits для ресурсов
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

env:
  # Требуется переменная окружения для фича-флага
  ENABLE_FEATURE_X: "false" 

livenessProbe:
  # Требуется указать путь (/ping) и параметры задержки/периода
  path: "/ping"
  initialDelaySeconds: 10
  periodSeconds: 15
  timeoutSeconds: 5 

readinessProbe:
  # Требуется указать путь (/ping) и параметры задержки/периода
  path: "/ping"
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5 