# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import hotel_pb2 as hotel__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hotel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HotelServiceStub(object):
    """gRPC-hotel srvice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateHotel = channel.unary_unary(
                '/hotel.HotelService/CreateHotel',
                request_serializer=hotel__pb2.CreateHotelRequest.SerializeToString,
                response_deserializer=hotel__pb2.HotelResponse.FromString,
                _registered_method=True)
        self.ListHotels = channel.unary_unary(
                '/hotel.HotelService/ListHotels',
                request_serializer=hotel__pb2.HotelsListRequest.SerializeToString,
                response_deserializer=hotel__pb2.HotelsListResponse.FromString,
                _registered_method=True)


class HotelServiceServicer(object):
    """gRPC-hotel srvice
    """

    def CreateHotel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHotels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateHotel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHotel,
                    request_deserializer=hotel__pb2.CreateHotelRequest.FromString,
                    response_serializer=hotel__pb2.HotelResponse.SerializeToString,
            ),
            'ListHotels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHotels,
                    request_deserializer=hotel__pb2.HotelsListRequest.FromString,
                    response_serializer=hotel__pb2.HotelsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel.HotelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hotel.HotelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HotelService(object):
    """gRPC-hotel srvice
    """

    @staticmethod
    def CreateHotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.HotelService/CreateHotel',
            hotel__pb2.CreateHotelRequest.SerializeToString,
            hotel__pb2.HotelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHotels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hotel.HotelService/ListHotels',
            hotel__pb2.HotelsListRequest.SerializeToString,
            hotel__pb2.HotelsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
