{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (.Values.appLabel | default .Release.Name) }}
  labels:
    app: {{ .Values.appLabel | default .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appLabel | default .Release.Name }}
{{- end }}
