apiVersion: v1
kind: Service
metadata:
  name: booking-service # Именно на этот хост будем ссылаться в Istio
spec:
  selector:
    app: booking-service # Сервис направляет трафик на ВСЕ поды с этой меткой (и v1, и v2)
  ports:
  - port: 80
    targetPort: 8080

#kubectl apply -f booking-service.yaml