version: "3.8"

services:
  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-service
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://booking-db:5432/booking
      SPRING_DATASOURCE_USERNAME: booking
      SPRING_DATASOURCE_PASSWORD: booking
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - hotelio-net
    depends_on:
      - booking-db

  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
  booking-db-data:

networks:
  hotelio-net:
    external: true