// <auto-generated />
using System;
using Hotelio.PromoCodeService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotelio.PromoCodeService.Migrations
{
    [DbContext(typeof(PromoCodeDbContext))]
    partial class PromoCodeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotelio.PromoCodeService.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("VipOnly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("promocode", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TESTCODE1",
                            Description = "Обычный промокод",
                            Discount = 10.0m,
                            Expired = false,
                            ValidUntil = new DateTime(2099, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VipOnly = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "TESTCODE-VIP",
                            Description = "Только для VIP",
                            Discount = 20.0m,
                            Expired = false,
                            ValidUntil = new DateTime(2099, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VipOnly = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "TESTCODE-OLD",
                            Description = "Истёкший промокод",
                            Discount = 5.0m,
                            Expired = true,
                            ValidUntil = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VipOnly = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
