"""empty message

Revision ID: 943731a78a29
Revises: fe2948d4c68d
Create Date: 2025-08-14 11:23:49.224418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943731a78a29'
down_revision: Union[str, Sequence[str], None] = 'fe2948d4c68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_history', sa.Column('reason', sa.String(length=512), nullable=False))
    op.add_column('booking_history', sa.Column('created', sa.Boolean(), nullable=False))
    op.alter_column('booking_history', 'discount_percent',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('booking_history', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking_history', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('booking_history', 'discount_percent',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('booking_history', 'created')
    op.drop_column('booking_history', 'reason')
    # ### end Alembic commands ###
